
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-27T14:40:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "77084f1e4c2c0be407e032d444fb19e4be4b0f37",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
